version: '3.7'

services:
    postgres:
        image: 'postgres:12-alpine'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        env_file:
            - .env.prod.db
        ports:
            - "5432:5432"
        networks:
            custom:
                ipv4_address: 172.20.0.4

    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn models_api.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
            - static_files:/home/app/web/static_files
        expose:
            - 8000
        env_file:
            - .env.prod
        extra_hosts:
            - "dockerhost:172.20.0.1"
        networks:
            custom:
                ipv4_address: 172.20.0.2
        depends_on:
            - postgres

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
        volumes:
            - static_files:/home/app/web/static_files
        networks:
            custom:
                ipv4_address: 172.20.0.3

networks:
    custom:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16

volumes:
    postgres_data:
    static_files: