version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:12-alpine'
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    env_file:
        - .env.prod.db
    ports:
        - "5432:5432"


volumes:
  postgres_data: