# Generated by Django 3.0.4 on 2020-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='Nobody', max_length=200),
        ),
    ]
